Fix failing eden tests
Multiple patches in this PR:
* Increased the default EVE version to the latest 12.4
* Removed workflow dependency on Smoke test suite. With reusable
  workflows this does not work properly in the EVE repository.
  The other test suites are triggered regardless of the outcome
  of Smoke tests. The only effect this dependency has, is that other
  workflows are delayed from starting until Smoke tests finish,
  increasing the total execution time of all tests.
* Moved tests that depend on virtualization (apps must be deployed
  inside VMs) to a separate test suite. The primary reason is that the
  HW-assisted nested virtualization is performing poorly on the buildjet
  runners and we are getting many failures (not related to EVE code).
  For every other test it is therefore better to run EVE with
  acceleration disabled. A secondary reason is that most of these tests
  are from the networking test suite, which is already quite long and
  takes well over an hour to execute. It therefore makes sense to move
  some tests to a different test suite.
  Please note that when the Virtualization test suite is run locally,
  all tests are passing. However, on buildjet runners they are expected
  to fail until we resolve the issue with the nested virtualization.
* Fixed 'eden pod modify' (wrong timeout + app state to wait for had to
  be modified to reflect recent EVE changes)
* Fixed ctrl_cert_change test (improper use of -check-new)
* App 'nodered' needs more time to get deployed
* Test publish_location is now skipped and likely will be removed. This
  is because after the recent changes in the EVE/wwan microservice,
  injecting a fake GPS location data is no longer possible.
* Modified EVE-upgrade tests to use newer base EVE version (> 12.0).
  This is because the policy_version of fscrypt was bumped from 1 to 2
  and this change is not backward compatible. Meaning we cannot
  downgrade from 12.X to 11.Y or older.

Signed-off-by: Milan Lenco <milan@zededa.com>

diff --git a/.github/actions/setup-environment/action.yml b/.github/actions/setup-environment/action.yml
--- a/.github/actions/setup-environment/action.yml
+++ b/.github/actions/setup-environment/action.yml
@@ -14,6 +14,8 @@ inputs:
     type: string
   artifact_run_id:
     type: string
+  require_virtualization:
+    type: bool
 
 runs:
   using: 'composite'
@@ -48,7 +50,12 @@ runs:
     - name: Configure
       run: |
         ./eden config add default
-        if lscpu | grep -oEq "vmx|svm"; then
+        require_virt="${{ inputs.require_virtualization }}"
+        if [[ "$require_virt" == "true" ]]; then
+          if ! lscpu | grep -oEq "vmx|svm"; then
+            echo "Missing required HW-assisted virtualization support"
+            exit 1
+          fi
           ./eden config set default --key=eve.accel --value=true
         else
           ./eden config set default --key=eve.accel --value=false
