check exit code of getting IP from gcp; adds info to artifact
Signed-off-by: Petr Fedchenkov <giggsoff@gmail.com>

diff --git a/.github/workflows/eden_gcp.yml b/.github/workflows/eden_gcp.yml
--- a/.github/workflows/eden_gcp.yml
+++ b/.github/workflows/eden_gcp.yml
@@ -59,9 +59,10 @@ jobs:
           ./eden utils gcp image --image-name eve-eden-actions-${{ matrix.hv }}-${{github.run_number}} -k "$GOOGLE_APPLICATION_CREDENTIALS" upload
           ./eden utils gcp vm --image-name eve-eden-actions-${{ matrix.hv }}-${{github.run_number}} --vm-name eve-eden-actions-${{ matrix.hv }}-${{github.run_number}} -k "$GOOGLE_APPLICATION_CREDENTIALS" run
           ./eden start
-          BWD=$(./eden utils gcp vm get-ip --vm-name eve-eden-actions-${{ matrix.hv }}-${{github.run_number}} -k "$GOOGLE_APPLICATION_CREDENTIALS")
+          sleep 5
+          BWD=$(./eden utils gcp vm get-ip --vm-name eve-eden-actions-${{ matrix.hv }}-${{github.run_number}} -k "$GOOGLE_APPLICATION_CREDENTIALS") || { echo "cannot obtain IP"; exit 1; }
           echo "the IP is $BWD"
-          ./eden utils gcp firewall -k "$GOOGLE_APPLICATION_CREDENTIALS" --source-range $BWD --name eden-actions-${{ matrix.hv }}-${{github.run_number}}
+          ./eden utils gcp firewall -k "$GOOGLE_APPLICATION_CREDENTIALS" --source-range $BWD --name eden-actions-${{ matrix.hv }}-${{github.run_number}} || { echo "cannot set firewall"; exit 1; }
           ./eden eve onboard
           echo > tests/workflow/testdata/eden_stop.txt
       - name: Test
@@ -71,6 +72,7 @@ jobs:
         if: ${{ always() }}
         run: |
           ./eden log --format json > trace.log
+          ./eden info > info.log
       - name: Clean
         if: ${{ always() }}
         run: |
@@ -83,4 +85,6 @@ jobs:
         uses: actions/upload-artifact@v2
         with:
           name: eden-report-${{ matrix.hv }}
-          path: ${{ github.workspace }}/trace.log
+          path: |
+            ${{ github.workspace }}/trace.log
+            ${{ github.workspace }}/info.log
